import Head from 'next/head'
import { useEffect, useState } from 'react'

import styles from '@/styles/Home.module.css'

import InputForm from '@/components/InputForm'
import ListData from '@/components/ListData'
import Filter from '@/components/Filter'

export default function Home() {
  let [ data, setData ] = useState([] as any);

  useEffect(() => {
    fetch("http://localhost:3000/api")
      .then(res => res.json())
      .then(data => setData(data.data))
  }, []);

  const create = (id: string, date: Date, amount: number, retailer: string) => {
    setData([
      ...data,
      { id, date, amount, retailer }
    ])
  }

  return (
    data ? 
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <InputForm create={create} />
          <ListData data={data} />
          <Filter />
        </main>
      </> : "Loading ..."
  )
}
